# Generated by Django 6.0.2 on 2026-02-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
    ]
