# Generated by Django 6.0.2 on 2026-02-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_earning_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
